// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3hk5wBaTaEkkkNwmRJY_jQNy478Uz4iI',
    appId: '1:136510526162:web:a39c720e2ae91bce7e130b',
    messagingSenderId: '136510526162',
    projectId: 'negoto-6e1f8',
    authDomain: 'negoto-6e1f8.firebaseapp.com',
    storageBucket: 'negoto-6e1f8.appspot.com',
    measurementId: 'G-0LFX846ZB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObk_7ppFKy_PuYgXpiHc2mCd_rPKALGU',
    appId: '1:136510526162:android:5815f2fe264ecdd77e130b',
    messagingSenderId: '136510526162',
    projectId: 'negoto-6e1f8',
    storageBucket: 'negoto-6e1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXXenccAjyc6swhvkHZ4TiwpAutJisGo',
    appId: '1:136510526162:ios:4669204e85d96ac87e130b',
    messagingSenderId: '136510526162',
    projectId: 'negoto-6e1f8',
    storageBucket: 'negoto-6e1f8.appspot.com',
    iosClientId: '136510526162-grh5eh7eq8f50icl5o7usuna1t16ife6.apps.googleusercontent.com',
    iosBundleId: 'com.wamteam.negoto',
  );
}
